export const iconMap = {
  ontology: "diagram-tree",
  objectType: "cube",
  actionType: "play",
  linkType: "link",
  interfaceType: "interface",
  dataset: "database",
  folder: "folder-close",
  project: "projects",
  user: "person",
  group: "people",
  function: "function",
  webhook: "globe-network",
  media: "media",
  monitor: "eye-open",
  settings: "cog",
  search: "search",
  filter: "filter",
  add: "plus",
  delete: "trash",
  edit: "edit",
  refresh: "refresh",
  download: "download",
  upload: "upload",
} as const;
