import * as fs from "node:fs";
import * as path from "node:path";
import { loadProjectConfig } from "../config/project-config.js";
import { log, error, bold, dim, spinner } from "../output.js";
import type { ParsedArgs } from "../cli.js";

async function generateTypes(args: ParsedArgs): Promise<void> {
  const config = loadProjectConfig();

  const conjureDir =
    typeof args.flags["conjure-dir"] === "string"
      ? args.flags["conjure-dir"]
      : config.conjureDir;

  const outputDir =
    typeof args.flags["output-dir"] === "string"
      ? args.flags["output-dir"]
      : config.outputDir;

  log("");
  log(bold("Generating TypeScript types from Conjure definitions"));
  log("");
  log(`  Source:  ${conjureDir}`);
  log(`  Output:  ${outputDir}`);
  log("");

  // Validate source directory exists
  const resolvedConjureDir = path.resolve(conjureDir);
  if (!fs.existsSync(resolvedConjureDir)) {
    error(`Conjure directory not found: ${resolvedConjureDir}`);
    error("Create a 'conjure/' directory with your YAML definitions.");
    process.exitCode = 1;
    return;
  }

  // Find YAML files
  const yamlFiles = fs
    .readdirSync(resolvedConjureDir)
    .filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"))
    .map((f) => path.join(resolvedConjureDir, f));

  if (yamlFiles.length === 0) {
    error(`No YAML files found in ${resolvedConjureDir}`);
    process.exitCode = 1;
    return;
  }

  log(dim(`  Found ${yamlFiles.length} YAML definition file(s)`));

  const sp = spinner("Compiling Conjure definitions...");

  try {
    // Import workspace dependencies
    const { loadConjureDirectory } = await import(
      "@openfoundry/conjure-compiler"
    );
    const { generateFromIr } = await import(
      "@openfoundry/conjure-codegen"
    );

    // Step 1: Compile YAML files to Conjure IR
    sp.update("Compiling Conjure YAML to IR...");
    const ir = await loadConjureDirectory(resolvedConjureDir);

    // Step 2: Generate TypeScript from IR
    sp.update("Generating TypeScript types...");
    const generatedFiles = generateFromIr(ir);

    // Step 3: Write output files
    sp.update("Writing output files...");
    const resolvedOutputDir = path.resolve(outputDir);

    if (!fs.existsSync(resolvedOutputDir)) {
      fs.mkdirSync(resolvedOutputDir, { recursive: true });
    }

    let fileCount = 0;
    for (const file of generatedFiles) {
      const filePath = path.join(resolvedOutputDir, file.path);
      const fileDir = path.dirname(filePath);
      if (!fs.existsSync(fileDir)) {
        fs.mkdirSync(fileDir, { recursive: true });
      }
      fs.writeFileSync(filePath, file.content, "utf-8");
      fileCount++;
    }

    sp.stop(`Generated ${fileCount} TypeScript file(s)`);
    log(dim(`  Output written to ${resolvedOutputDir}`));
  } catch (err) {
    sp.stop();
    throw err;
  }
}

async function generateOntology(args: ParsedArgs): Promise<void> {
  const config = loadProjectConfig();

  const ontologyFile =
    typeof args.flags["ontology-file"] === "string"
      ? args.flags["ontology-file"]
      : config.ontologyFile;

  const outputDir =
    typeof args.flags["output-dir"] === "string"
      ? args.flags["output-dir"]
      : config.outputDir;

  log("");
  log(bold("Generating typed SDK from ontology definition"));
  log("");
  log(`  Ontology: ${ontologyFile}`);
  log(`  Output:   ${outputDir}`);
  log("");

  const resolvedOntologyFile = path.resolve(ontologyFile);
  if (!fs.existsSync(resolvedOntologyFile)) {
    error(`Ontology file not found: ${resolvedOntologyFile}`);
    error("Specify the path with --ontology-file or set it in foundry.config.json.");
    process.exitCode = 1;
    return;
  }

  const sp = spinner("Reading ontology definition...");

  try {
    const raw = fs.readFileSync(resolvedOntologyFile, "utf-8");

    // Determine if YAML or JSON
    let ontologyDef: Record<string, unknown>;
    if (
      resolvedOntologyFile.endsWith(".yaml") ||
      resolvedOntologyFile.endsWith(".yml")
    ) {
      // Use conjure-compiler's YAML parsing
      const { parseConjureYaml } = await import("@openfoundry/conjure-compiler");
      ontologyDef = parseConjureYaml(raw) as unknown as Record<string, unknown>;
    } else {
      ontologyDef = JSON.parse(raw) as Record<string, unknown>;
    }

    sp.update("Generating TypeScript interfaces...");

    const resolvedOutputDir = path.resolve(outputDir);
    if (!fs.existsSync(resolvedOutputDir)) {
      fs.mkdirSync(resolvedOutputDir, { recursive: true });
    }

    // Generate ontology types
    const objectTypes = ontologyDef["objectTypes"] as
      | Record<string, unknown>[]
      | undefined;
    const lines: string[] = [];

    lines.push("// Auto-generated by @openfoundry/sdk-cli");
    lines.push("// Do not edit manually");
    lines.push("");

    if (objectTypes && Array.isArray(objectTypes)) {
      for (const objType of objectTypes) {
        const typeName = objType["apiName"] as string;
        const properties = objType["properties"] as
          | Record<string, unknown>[]
          | undefined;

        lines.push(`export interface ${typeName} {`);
        if (properties && Array.isArray(properties)) {
          for (const prop of properties) {
            const propName = prop["apiName"] as string;
            const propType = mapOntologyType(prop["type"] as string);
            lines.push(`  ${propName}: ${propType};`);
          }
        }
        lines.push("}");
        lines.push("");
      }
    }

    // Generate client interface
    lines.push("export interface OntologyClient {");
    if (objectTypes && Array.isArray(objectTypes)) {
      for (const objType of objectTypes) {
        const typeName = objType["apiName"] as string;
        const camelName =
          typeName.charAt(0).toLowerCase() + typeName.slice(1);
        lines.push(`  ${camelName}: ObjectSet<${typeName}>;`);
      }
    }
    lines.push("}");
    lines.push("");

    lines.push("export interface ObjectSet<T> {");
    lines.push("  get(primaryKey: string): Promise<T>;");
    lines.push("  list(options?: ListOptions): Promise<Page<T>>;");
    lines.push(
      "  where(filter: FilterExpression<T>): ObjectSet<T>;",
    );
    lines.push("}");
    lines.push("");

    lines.push("export interface ListOptions {");
    lines.push("  pageSize?: number;");
    lines.push("  pageToken?: string;");
    lines.push("}");
    lines.push("");

    lines.push("export interface Page<T> {");
    lines.push("  data: T[];");
    lines.push("  nextPageToken?: string;");
    lines.push("}");
    lines.push("");

    lines.push("export type FilterExpression<T> = {");
    lines.push("  [K in keyof T]?: T[K] | { $eq?: T[K]; $neq?: T[K]; $gt?: T[K]; $lt?: T[K] };");
    lines.push("};");
    lines.push("");

    const ontologyOutput = path.join(resolvedOutputDir, "ontology.ts");
    fs.writeFileSync(ontologyOutput, lines.join("\n"), "utf-8");

    sp.stop("Generated ontology SDK types");
    log(dim(`  Output written to ${ontologyOutput}`));
  } catch (err) {
    sp.stop();
    throw err;
  }
}

function mapOntologyType(type: string): string {
  switch (type) {
    case "string":
      return "string";
    case "integer":
    case "long":
    case "double":
    case "float":
      return "number";
    case "boolean":
      return "boolean";
    case "datetime":
    case "timestamp":
      return "string";
    case "date":
      return "string";
    default:
      return "unknown";
  }
}

const SUBCOMMANDS: Record<string, (args: ParsedArgs) => Promise<void>> = {
  types: generateTypes,
  ontology: generateOntology,
};

export async function handleGenerate(args: ParsedArgs): Promise<void> {
  const sub = args.subcommand;

  if (!sub) {
    error(
      "Missing subcommand. Usage: openfoundry generate <types|ontology>",
    );
    process.exitCode = 1;
    return;
  }

  const handler = SUBCOMMANDS[sub];
  if (!handler) {
    error(`Unknown generate subcommand: ${sub}`);
    error("Available subcommands: types, ontology");
    process.exitCode = 1;
    return;
  }

  await handler(args);
}
