// ObjectSet types
export type {
  ObjectSetType,
  ObjectSet,
  BaseObjectSet,
  FilterObjectSet,
  UnionObjectSet,
  IntersectObjectSet,
  SubtractObjectSet,
  SearchAroundObjectSet,
  StaticObjectSet,
  ReferenceObjectSet,
  InterfaceBaseObjectSet,
  NearObjectSet,
  WithinObjectSet,
  IntersectsBboxObjectSet,
  IntersectsPolygonObjectSet,
  AllGeoObjectSet,
  NaturalLanguageObjectSet,
  DataframeObjectSet,
  VersionedObjectSet,
  GeoPoint,
  BoundingBox,
  GeoPolygon,
} from "./object-set-types.js";

// Filter types
export type {
  FilterType,
  Filter,
  AndFilter,
  OrFilter,
  NotFilter,
  EqualsFilter,
  ContainsFilter,
  StartsWithFilter,
  GtFilter,
  GteFilter,
  LtFilter,
  LteFilter,
  IsNullFilter,
  RangeFilter,
  InSetFilter,
  HasPropertyFilter,
  PhraseFilter,
  PrefixFilter,
  RegexFilter,
  GeoBoundingBoxFilter,
  GeoDistanceFilter,
  GeoPolygonFilter,
  GeoShapeFilter,
  RelativeTimeRangeFilter,
  AbsoluteTimeRangeFilter,
  StructFieldFilter,
  ArrayContainsFilter,
  ArrayContainsAllFilter,
  ArrayIsEmptyFilter,
  PropertyValue,
  GeoCoordinate,
  GeoJsonGeometry,
  GeoShapeRelation,
  TimeUnit,
} from "./filter-types.js";

// Aggregation types
export type {
  AggregationType,
  Aggregation,
  CountAggregation,
  MinAggregation,
  MaxAggregation,
  SumAggregation,
  AvgAggregation,
  ApproximateDistinctAggregation,
  ExactDistinctAggregation,
  ApproximatePercentileAggregation,
} from "./aggregations.js";

// Aggregation factory functions
export {
  count,
  min,
  max,
  sum,
  avg,
  approximateDistinct,
  exactDistinct,
  approximatePercentile,
} from "./aggregations.js";

// Query engine
export {
  ObjectSetQueryEngine,
  type ObjectSetDefinition,
  type WhereClause,
  type AggregationDef,
  type GroupByDef,
  type AggregationResult,
  type SearchOptions,
} from "./query-engine.js";

// Builder and filter helpers
export {
  ObjectSetBuilder,
  objectSet,
  staticObjectSet,
  interfaceObjectSet,
  dataframeObjectSet,
  // Filter factories
  eq,
  contains,
  startsWith,
  gt,
  gte,
  lt,
  lte,
  isNull,
  range,
  inSet,
  hasProperty,
  phrase,
  prefix,
  regex,
  and,
  or,
  not,
  geoBoundingBox,
  geoDistance,
  geoPolygon,
  relativeTimeRange,
  absoluteTimeRange,
  structField,
  arrayContains,
  arrayContainsAll,
  arrayIsEmpty,
} from "./object-set-builder.js";
